#
# To build use 'make -f Makefile.plain' in a shell

# This script must find the directory where Python.h is and
# the libpython2.7.so to link with. Other versions of Python 
# are untested but might work.
#


CC=gcc
LD=ld

CFLAGS=-I/usr/include/python2.7

LIBS=-lpython2.7 -lc -lm

OBJS = nk/NK.o \
	nk/Py_NK.o

all: so

so: $(OBJS)
	gcc -shared -o cyphesis-ai-genetic.so *.o
clean:
	rm -f *.o *.so


.cpp.o:
	$(CC) $(CFLAGS) -c $<
